// libs/react-native/src/components/GdInput/GdInput.tsx
import { useEffect, useRef, useState } from 'react';
import { Text, TextInput, View, type TextStyle } from 'react-native';
import {
  createInputStore,
  debounce,
  resolveInputStyle,
  type DesignCoreTheme,
  type InputColorVariantName,
} from 'gd-design-core';
import { pxToNumber } from '../../utils/pxToNumber';
import { toFontFamily } from '../../utils/toFontFamily';

export interface GdInputProps {
  value?: string;
  defaultValue?: string;
  placeholder?: string;
  label?: string;
  helperText?: string;
  disabled?: boolean;
  color?: InputColorVariantName;
  /** Mirrors `gd-input.ts`'s `debounce-callback-time` — ms delay before `onValueChange` fires
   *  after the last keystroke. Undefined means every keystroke dispatches immediately. */
  debounceCallbackTime?: number;
  onValueChange?: (value: string) => void;
  theme?: DesignCoreTheme;
}

/**
 * CTORNDSD-590 Input port — mirrors `libs/web-components/src/components/gd-input/gd-input.ts`'s
 * cursor-jump mitigation, adapted to React's controlled-component model instead of a direct-DOM
 * `activeElement` guard.
 *
 * RN's `TextInput` has no DOM `activeElement`/direct-value-write escape hatch the way a native
 * `<input>` does — this component keeps its own `localValue` state as the single source of truth
 * for what's rendered, and only re-syncs it from an external `value` prop change while the field
 * is NOT focused (`isFocusedRef`). An external write that arrives while the user is actively
 * typing is dropped, exactly like the Lit port's `activeElement` guard, and reconciled on blur
 * instead. `onChangeText` (RN's bare-string callback, unlike web's `ChangeEvent<HTMLInputElement>`
 * — the one confirmed permanent per-platform fork per `createInputStore.ts`'s own doc comment)
 * is wrapped with `gd-design-core`'s `debounce()` before calling `onValueChange`.
 *
 * NOT ported from `createInputStore`: `registerMouseDown`/`registerKeyDown`'s
 * `isMouseInteraction` tracking. That state exists solely to pick a focus-ring style for
 * mouse-vs-keyboard-Tab interaction — RN has no mouse pointer or Tab-key focus-traversal
 * convention on touch targets, so there is no RN-side consumer for this value. Documented as a
 * finding in `react-native/FINDINGS.md`, not a silent omission.
 *
 * Cursor-jump mitigation is implemented but NOT empirically verified on-device in this spike —
 * see `react-native/FINDINGS.md` for why (no simulator/device available in the environment
 * this port was authored in) and what a human must still confirm before treating this as closed.
 */
export function GdInput({
  value,
  defaultValue = '',
  placeholder,
  label,
  helperText,
  disabled = false,
  color = 'primary',
  debounceCallbackTime,
  onValueChange,
  theme = {},
}: GdInputProps) {
  const isControlled = value !== undefined;
  const [localValue, setLocalValue] = useState(value ?? defaultValue);
  const [isFocused, setIsFocused] = useState(false);
  const isFocusedRef = useRef(false);
  const storeRef = useRef(createInputStore({ debounceCallbackTime }));
  const debouncedDispatchRef = useRef<((next: string) => void) | undefined>(undefined);
  const onValueChangeRef = useRef(onValueChange);

  useEffect(() => {
    onValueChangeRef.current = onValueChange;
  }, [onValueChange]);

  useEffect(() => {
    storeRef.current.getState().setDebounceCallbackTime(debounceCallbackTime);
    debouncedDispatchRef.current = undefined;
  }, [debounceCallbackTime]);

  useEffect(() => {
    if (!isControlled || isFocusedRef.current) return;
    setLocalValue(value ?? '');
  }, [value, isControlled]);

  const getDebouncedDispatch = (): ((next: string) => void) => {
    const ms = storeRef.current.getState().debounceCallbackTime;
    if (typeof ms !== 'number') return (next) => onValueChangeRef.current?.(next);
    if (!debouncedDispatchRef.current) {
      debouncedDispatchRef.current = debounce((next: string) => onValueChangeRef.current?.(next), ms);
    }
    return debouncedDispatchRef.current;
  };

  const handleChangeText = (text: string) => {
    setLocalValue(text);
    getDebouncedDispatch()(text);
  };

  const handleFocus = () => {
    isFocusedRef.current = true;
    setIsFocused(true);
  };

  const handleBlur = () => {
    isFocusedRef.current = false;
    setIsFocused(false);
    // Reconciles any external `value` write dropped while focused (the guard above).
    if (isControlled && value !== localValue) setLocalValue(value ?? '');
  };

  const resolved = resolveInputStyle(theme, color);
  const textColor = disabled ? resolved.disabledColor : resolved.color;
  // `resolveInputStyle` exposes no `fontWeight`, so this resolves to the family's regular face.
  const fontFamily = toFontFamily(resolved.fontFamily);

  return (
    <View style={{ gap: pxToNumber(resolved.wrapperGap), alignItems: 'flex-start' }}>
      {label ? (
        <Text
          style={{
            color: resolved.labelColor,
            fontFamily,
            fontSize: pxToNumber(resolved.labelFontSize),
            lineHeight: pxToNumber(resolved.labelLineHeight),
          }}
        >
          {label}
        </Text>
      ) : null}
      <View
        style={{
          borderWidth: pxToNumber(resolved.borderWidth),
          borderColor: resolved.borderColor,
          borderRadius: pxToNumber(resolved.borderRadius),
          paddingHorizontal: pxToNumber(resolved.horizontalPadding),
          width: '100%',
        }}
      >
        <TextInput
          value={localValue}
          onChangeText={handleChangeText}
          onFocus={handleFocus}
          onBlur={handleBlur}
          editable={!disabled}
          placeholder={placeholder}
          placeholderTextColor={resolved.disabledColor}
          style={[
            {
              fontFamily,
              fontSize: pxToNumber(resolved.fontSize),
              color: textColor,
              height: 40,
            },
            // react-native-web's `TextInput` compiles to a real DOM `<input>`, which picks up
            // the browser's own native focus ring independently of this wrapper `View`'s border
            // — the two rendered together is the doubled ring. `outlineStyle` is a
            // react-native-web-only style extension (no-op on iOS/Android) for suppressing it;
            // not in RN's own `TextStyle` type, hence the cast.
            { outlineStyle: 'none' } as TextStyle,
          ]}
        />
        {isFocused ? (
          // Real `input.ts` draws focus as a separate `.Input__outline` layer — `outline: 2px
          // solid colors.border.focus` at `outlineOffset: 3px` — sitting outside the border,
          // gap and all, while the border itself stays exactly as it was. RN has no `outline`
          // primitive, so this approximates the same "offset ring, border untouched" look with
          // an absolutely-positioned sibling `View`, inset by -(offset + width) = -5 on every
          // edge so its own 2px border lands in the same 3px-to-5px-outside band a CSS outline
          // would occupy. `pointerEvents: 'none'` keeps it from intercepting the tap that
          // toggles focus.
          <View
            testID="gd-input-focus-ring"
            style={{
              position: 'absolute',
              top: -5,
              left: -5,
              right: -5,
              bottom: -5,
              borderWidth: 2,
              borderColor: resolved.focusColor,
              borderRadius: pxToNumber(resolved.borderRadius),
              pointerEvents: 'none',
            }}
          />
        ) : null}
      </View>
      {helperText ? (
        <Text
          style={{
            color: resolved.helperTextColor,
            fontFamily,
            fontSize: pxToNumber(resolved.helperFontSize),
            lineHeight: pxToNumber(resolved.helperLineHeight),
          }}
        >
          {helperText}
        </Text>
      ) : null}
    </View>
  );
}

// libs/web-components/src/components/gd-input/gd-input.ts
import { LitElement, html, css, nothing, type PropertyValues } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import { styleMap } from 'lit/directives/style-map.js';
import { input } from 'gd-design-library/tokens';
import { resolveThemeTree } from '../../../../design-core/src/utils/resolveThemeTree';
import { get } from '../../../../design-core/src/utils/get';
import { createInputStore, debounce } from '../../../../design-core/src/stores/createInputStore';
import { InputColorVariantName } from '../../../../design-core/src/tokenResolvers/input';
import { DesignCoreTheme } from '../../../../design-core/src/types';

interface ResolvedInputTokens {
  fontFamily: string | number;
  fontSize: string | number;
  color: string;
  disabledColor: string;
  border: string;
  labelColor: string;
  helperTextColor: string;
  wrapperGap: string | number;
  labelFontSize: string | number;
  labelLineHeight: string | number;
  helperFontSize: string | number;
  helperLineHeight: string | number;
  zIndex: string | number;
  horizontalPadding: string | number;
  borderRadius: string | number;
}

/**
 * Resolves the REAL `input` object (`gd-design-library/tokens`) against `theme` — the
 * single-source-of-truth replacement for the old, hand-mirrored `resolveInputStyle` in
 * `gd-design-core` (deleted; see that package's `tokenResolvers/input.ts` for the exact real
 * paths this reads: `input.wrapper.withGap.gap`, `input.helper.default.{sm,md}`,
 * `input.helper.<variant>.sm.color`, `input.input.default.padding`,
 * `input.input.defaultInteraction['& + .Input__border'].borderRadius`,
 * `input.input.<variant>['& + .Input__border'].border`). `fontFamily`/`fontSize` are the one
 * exception — the real `input.ts` object has neither (the real `<input>` inherits both from the
 * app's global CSS reset), so those two are resolved from the same shared `font.*` theme tokens
 * every other component uses, same as `gd-button.ts`.
 */
function resolveInputTokens(theme: DesignCoreTheme, color: InputColorVariantName): ResolvedInputTokens {
  const resolved = resolveThemeTree(input, theme) as unknown as {
    wrapper: { withGap: { gap: string | number } };
    input: {
      default: {
        color: string;
        padding: string | number;
        '&:not([type="radio"], [type="checkbox"], [type="range"])': { zIndex: string | number };
        '&[readonly], &:disabled': { color: string };
      };
      defaultInteraction: { '& + .Input__border': { borderRadius: string | number } };
    } & Record<InputColorVariantName, { '& + .Input__border': { border: string } }>;
    helper: {
      default: {
        sm: { fontSize: string | number; lineHeight: string | number };
        md: { color: string; fontSize: string | number; lineHeight: string | number };
      };
    } & Record<InputColorVariantName, { sm: { color?: string } }>;
  };

  const inputDefault = resolved.input.default;
  const colorTokens = resolved.input[color] ?? resolved.input.primary;
  const helperColorTokens = resolved.helper[color] ?? resolved.helper.primary;

  return {
    fontFamily: get(theme, 'font.family', '"Fira Sans", sans-serif'),
    fontSize: get(theme, 'font.size.p', '16px'),
    color: inputDefault.color,
    disabledColor: inputDefault['&[readonly], &:disabled'].color,
    border: colorTokens['& + .Input__border'].border,
    labelColor: resolved.helper.default.md.color,
    helperTextColor: helperColorTokens.sm.color ?? resolved.helper.default.md.color,
    wrapperGap: resolved.wrapper.withGap.gap,
    labelFontSize: resolved.helper.default.md.fontSize,
    labelLineHeight: resolved.helper.default.md.lineHeight,
    helperFontSize: resolved.helper.default.sm.fontSize,
    helperLineHeight: resolved.helper.default.sm.lineHeight,
    zIndex: inputDefault['&:not([type="radio"], [type="checkbox"], [type="range"])'].zIndex,
    horizontalPadding: inputDefault.padding,
    borderRadius: resolved.input.defaultInteraction['& + .Input__border'].borderRadius,
  };
}

/**
 * Input port (per the implementation plan's Migration Example) — the highest-risk
 * small atom: a controlled `value` over a custom-element boundary has no reconciliation
 * layer protecting cursor position the way React's controlled-input diffing does.
 *
 * Cursor-jump mitigation (must be empirically verified, not assumed):
 * `.value` is never template-bound directly (`.value=${this.value}` would let every
 * external property write clobber the live DOM value unconditionally). Instead this
 * component tracks whether the pending `value` change originated from the user's own
 * keystroke (`_lastInternalValue`) or from an external property/attribute write. An
 * external write while the native `<input>` still has focus is dropped rather than
 * applied — the concrete activeElement-guard from the plan — and only re-applied once
 * the input actually loses focus. Record in FINDINGS.md whether this drop-while-focused
 * behavior is itself an acceptable trade (vs. the alternative of letting the cursor jump).
 *
 * Visual-fidelity fixes (found while comparing against the real Storybook Input, the
 * originally reported gap): the real component draws its visible border on an
 * absolutely-positioned sibling `<span>` (`.Input__border`), not the input's own CSS
 * border, and layers a second sibling (`.Input__outline`) for the focus ring — both with
 * **square corners** (`radius.none`), not rounded. It also renders an optional `label`
 * (above, 14px/#000) and `helperText` (below, 12px, color mapped by `color`) — entirely
 * missing from the original port. `:focus-visible` is used natively here for the ring
 * (the real component manually mirrors keyboard-vs-mouse interaction since it predates
 * broad `:focus-visible` support), which is a closer, simpler equivalent, not a lesser one.
 */
@customElement('gd-input')
export class GdInput extends LitElement {
  static styles = css`
    :host {
      display: inline-block;
    }
    .outer {
      display: inline-flex;
      flex-direction: column;
      align-items: flex-start;
    }
    .row {
      position: relative;
      display: inline-flex;
      align-items: center;
      width: 100%;
      box-sizing: border-box;
    }
    input {
      position: relative;
      border: none;
      outline: none;
      background: transparent;
      font: inherit;
      color: inherit;
      width: 100%;
      height: 40px;
      box-sizing: border-box;
    }
    input:disabled {
      cursor: default;
    }
    input::placeholder {
      color: var(--gd-input-placeholder-color, #a3a3a3);
    }
    .border,
    .outline {
      position: absolute;
      inset: 0;
      pointer-events: none;
      box-sizing: border-box;
    }
    .border {
      border-style: solid;
    }
    .outline {
      outline-style: none;
    }
    input:focus-visible ~ .outline {
      outline-style: solid;
      outline-width: 2px;
      outline-offset: 3px;
    }
  `;

  @property({ type: String }) value = '';
  @property({ type: String }) placeholder = '';
  @property({ type: String }) label = '';
  @property({ type: String, attribute: 'helper-text' }) helperText = '';
  @property({ type: Boolean, reflect: true }) disabled = false;
  @property({ type: String }) color: InputColorVariantName = 'primary';
  @property({ type: Number, attribute: 'debounce-callback-time' }) debounceCallbackTime?: number;
  @property({ attribute: false }) theme: DesignCoreTheme = {};

  @query('input') private _input!: HTMLInputElement;

  private _store = createInputStore({ debounceCallbackTime: this.debounceCallbackTime });
  private _unsubscribe?: () => void;
  /** Value last written into the DOM by the user's own keystroke — distinguishes an
   *  internal echo (safe, already live in the DOM) from an external prop write (guarded). */
  private _lastInternalValue = this.value;
  private _debouncedDispatch?: (value: string) => void;

  connectedCallback() {
    super.connectedCallback();
    this._unsubscribe = this._store.subscribe(() => this.requestUpdate());
  }

  disconnectedCallback() {
    this._unsubscribe?.();
    super.disconnectedCallback();
  }

  firstUpdated() {
    this._input.value = this.value;
  }

  willUpdate(changed: PropertyValues<this>) {
    if (changed.has('debounceCallbackTime')) {
      this._store.getState().setDebounceCallbackTime(this.debounceCallbackTime);
      this._debouncedDispatch = undefined;
    }
  }

  updated(changed: PropertyValues<this>) {
    if (!changed.has('value') || !this._input) return;

    if (this.value === this._lastInternalValue) return; // already live in the DOM from the keystroke itself

    const isFocused = this.shadowRoot?.activeElement === this._input;
    if (isFocused) return; // activeElement guard: drop the external write rather than jump the cursor

    this._input.value = this.value;
    this._lastInternalValue = this.value;
  }

  private _dispatchValue(value: string) {
    this.dispatchEvent(new CustomEvent('gd-input', { detail: { value }, bubbles: true, composed: true }));
  }

  private _getDebouncedDispatch(): (value: string) => void {
    const ms = this._store.getState().debounceCallbackTime;
    if (typeof ms !== 'number') return (value) => this._dispatchValue(value);
    if (!this._debouncedDispatch) this._debouncedDispatch = debounce((value: string) => this._dispatchValue(value), ms);
    return this._debouncedDispatch;
  }

  private _onInput(event: Event) {
    const newValue = (event.target as HTMLInputElement).value;
    this._lastInternalValue = newValue;
    this.value = newValue;
    this._getDebouncedDispatch()(newValue);
  }

  private _onMouseDown() {
    this._store.getState().registerMouseDown();
  }

  private _onKeyDown(event: KeyboardEvent) {
    this._store.getState().registerKeyDown(event.key === 'Tab');
  }

  private _onBlur() {
    this._store.getState().registerBlur();
    // Any external value dropped while focused (activeElement guard above) is reconciled here.
    if (this.value !== this._input.value) {
      this._input.value = this.value;
      this._lastInternalValue = this.value;
    }
  }

  render() {
    const resolved = resolveInputTokens(this.theme, this.color);
    const focusColor = (this.theme.colors as { border?: { focus?: string } } | undefined)?.border?.focus ?? '#0069B4';
    const textColor = this.disabled ? resolved.disabledColor : resolved.color;

    const outerStyle = { gap: `${resolved.wrapperGap}` };
    const rowStyle = {
      fontFamily: `${resolved.fontFamily}`,
      fontSize: `${resolved.fontSize}`,
      color: textColor,
      zIndex: `${resolved.zIndex}`,
      padding: `0 ${resolved.horizontalPadding}`,
      '--gd-input-placeholder-color': resolved.disabledColor,
    };
    const borderStyle = {
      border: resolved.border,
      borderRadius: `${resolved.borderRadius}`,
    };
    const outlineStyle = { outlineColor: focusColor, borderRadius: `${resolved.borderRadius}` };
    // Reuses the SAME resolved.fontFamily as the `<input>` itself (rowStyle above) — the real
    // InputHelper (label/helperText) has no explicit fontFamily of its own either, relying on
    // ambient inheritance from the host app's global reset, which would leave these two spans
    // free to silently diverge from the input's own (explicitly-resolved) font in a standalone
    // render with no such reset present.
    const labelStyle = {
      color: resolved.labelColor,
      fontFamily: `${resolved.fontFamily}`,
      fontSize: `${resolved.labelFontSize}`,
      lineHeight: `${resolved.labelLineHeight}`,
    };
    const helperStyle = {
      color: resolved.helperTextColor,
      fontFamily: `${resolved.fontFamily}`,
      fontSize: `${resolved.helperFontSize}`,
      lineHeight: `${resolved.helperLineHeight}`,
    };

    return html`
      <div class="outer" style=${styleMap(outerStyle)}>
        ${this.label ? html`<span class="label" style=${styleMap(labelStyle)}>${this.label}</span>` : nothing}
        <div class="row" style=${styleMap(rowStyle)}>
          <slot name="adornment-start"></slot>
          <input
            placeholder=${this.placeholder}
            ?disabled=${this.disabled}
            @input=${this._onInput}
            @mousedown=${this._onMouseDown}
            @keydown=${this._onKeyDown}
            @blur=${this._onBlur}
          />
          <span class="border" style=${styleMap(borderStyle)}></span>
          <span class="outline" style=${styleMap(outlineStyle)}></span>
          <slot name="adornment-end"></slot>
        </div>
        ${this.helperText
          ? html`<span class="helper" style=${styleMap(helperStyle)}>${this.helperText}</span>`
          : nothing}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gd-input': GdInput;
  }
}
